// <auto-generated />
using System;
using GymSystem.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GymSystem.Db.Migrations
{
    [DbContext(typeof(Model))]
    partial class ModelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GymSystem.Db.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("city");

                    b.Property<string>("code");

                    b.Property<string>("street");

                    b.HasKey("Id");

                    b.ToTable("AddressSet");
                });

            modelBuilder.Entity("GymSystem.Db.Entrance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BeginDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<int?>("EntranceTypeId");

                    b.Property<int?>("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("EntranceTypeId");

                    b.HasIndex("PersonId");

                    b.ToTable("EntranceSet");
                });

            modelBuilder.Entity("GymSystem.Db.EntranceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date");

                    b.Property<int?>("EntranceId");

                    b.HasKey("Id");

                    b.HasIndex("EntranceId");

                    b.ToTable("EntranceLogSet");
                });

            modelBuilder.Entity("GymSystem.Db.EntranceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Duration");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("EntranceTypeSet");
                });

            modelBuilder.Entity("GymSystem.Db.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdressId");

                    b.Property<string>("Mail");

                    b.Property<string>("Name");

                    b.Property<string>("Pesel");

                    b.Property<string>("Phone");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.HasIndex("AdressId");

                    b.ToTable("PersonSet");
                });

            modelBuilder.Entity("GymSystem.Db.Entrance", b =>
                {
                    b.HasOne("GymSystem.Db.EntranceType", "EntranceType")
                        .WithMany("Entrance")
                        .HasForeignKey("EntranceTypeId");

                    b.HasOne("GymSystem.Db.Person", "Person")
                        .WithMany("Entrance")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("GymSystem.Db.EntranceLog", b =>
                {
                    b.HasOne("GymSystem.Db.Entrance", "Entrance")
                        .WithMany("EntranceLog")
                        .HasForeignKey("EntranceId");
                });

            modelBuilder.Entity("GymSystem.Db.Person", b =>
                {
                    b.HasOne("GymSystem.Db.Address", "Adress")
                        .WithMany("Person")
                        .HasForeignKey("AdressId");
                });
#pragma warning restore 612, 618
        }
    }
}
