//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://bit.ly/reswcodegen)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 01/12/2019 17:19:18
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace GymSystem.Localization
{
    using Windows.ApplicationModel.Resources;
    
    
    public sealed partial class Resources
    {
        
        private static ResourceLoader resourceLoader;
        
        static Resources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Resources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Resources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Resources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Add"
        /// </summary>
        public static string ButtonLabelAdd
        {
            get
            {
                return resourceLoader.GetString("ButtonLabelAdd");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Add Entrance"
        /// </summary>
        public static string ButtonLabelAddEntrance
        {
            get
            {
                return resourceLoader.GetString("ButtonLabelAddEntrance");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Delete"
        /// </summary>
        public static string ButtonLabelDelete
        {
            get
            {
                return resourceLoader.GetString("ButtonLabelDelete");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "View Details"
        /// </summary>
        public static string ButtonLabelDetails
        {
            get
            {
                return resourceLoader.GetString("ButtonLabelDetails");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Filter by"
        /// </summary>
        public static string ButtonLabelFilter
        {
            get
            {
                return resourceLoader.GetString("ButtonLabelFilter");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Refresh"
        /// </summary>
        public static string ButtonLabelRefresh
        {
            get
            {
                return resourceLoader.GetString("ButtonLabelRefresh");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Address and personal data"
        /// </summary>
        public static string CollapseAddress
        {
            get
            {
                return resourceLoader.GetString("CollapseAddress");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Entrance"
        /// </summary>
        public static string CollapseEntrance
        {
            get
            {
                return resourceLoader.GetString("CollapseEntrance");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "City"
        /// </summary>
        public static string ColumnHeaderCity
        {
            get
            {
                return resourceLoader.GetString("ColumnHeaderCity");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "E-mail"
        /// </summary>
        public static string ColumnHeaderEmail
        {
            get
            {
                return resourceLoader.GetString("ColumnHeaderEmail");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Id"
        /// </summary>
        public static string ColumnHeaderId
        {
            get
            {
                return resourceLoader.GetString("ColumnHeaderId");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Name"
        /// </summary>
        public static string ColumnHeaderName
        {
            get
            {
                return resourceLoader.GetString("ColumnHeaderName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Phone"
        /// </summary>
        public static string ColumnHeaderPhone
        {
            get
            {
                return resourceLoader.GetString("ColumnHeaderPhone");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Postal Code"
        /// </summary>
        public static string ColumnHeaderPostalCode
        {
            get
            {
                return resourceLoader.GetString("ColumnHeaderPostalCode");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Street"
        /// </summary>
        public static string ColumnHeaderStreet
        {
            get
            {
                return resourceLoader.GetString("ColumnHeaderStreet");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Surname"
        /// </summary>
        public static string ColumnHeaderSurname
        {
            get
            {
                return resourceLoader.GetString("ColumnHeaderSurname");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "End date"
        /// </summary>
        public static string EntrancePropertiesEndDate
        {
            get
            {
                return resourceLoader.GetString("EntrancePropertiesEndDate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Price"
        /// </summary>
        public static string EntrancePropertiesPrice
        {
            get
            {
                return resourceLoader.GetString("EntrancePropertiesPrice");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Start date"
        /// </summary>
        public static string EntrancePropertiesStartDate
        {
            get
            {
                return resourceLoader.GetString("EntrancePropertiesStartDate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Type"
        /// </summary>
        public static string EntrancePropertiesType
        {
            get
            {
                return resourceLoader.GetString("EntrancePropertiesType");
            }
        }
    }
}
