//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntranceLog
    {
        public int Id { get; set; }
        public string Date { get; set; }
    
        public virtual Entrance Entrance { get; set; }
    }
}
